window.esdocSearchIndex = [
  [
    "reachhigh/src/stores/authstore.js~authstore",
    "class/src/stores/AuthStore.js~AuthStore.html",
    "<span>AuthStore</span> <span class=\"search-result-import-path\">reachhigh/src/stores/AuthStore.js</span>",
    "class"
  ],
  [
    "reachhigh/src/components/goals/goals.js~goals",
    "class/src/components/goals/Goals.js~Goals.html",
    "<span>Goals</span> <span class=\"search-result-import-path\">reachhigh/src/components/goals/Goals.js</span>",
    "class"
  ],
  [
    "reachhigh/src/stores/goalsstore.js~goalsstore",
    "class/src/stores/GoalsStore.js~GoalsStore.html",
    "<span>GoalsStore</span> <span class=\"search-result-import-path\">reachhigh/src/stores/GoalsStore.js</span>",
    "class"
  ],
  [
    "reachhigh/src/components/home/home.js~home",
    "function/index.html#static-function-Home",
    "<span>Home</span> <span class=\"search-result-import-path\">reachhigh/src/components/home/Home.js</span>",
    "function"
  ],
  [
    "reachhigh/src/components/navigation/horizontalnavigation.js~horizontalnavigation",
    "function/index.html#static-function-HorizontalNavigation",
    "<span>HorizontalNavigation</span> <span class=\"search-result-import-path\">reachhigh/src/components/navigation/HorizontalNavigation.js</span>",
    "function"
  ],
  [
    "reachhigh/src/components/auth/signin.js~signin",
    "class/src/components/auth/SignIn.js~SignIn.html",
    "<span>SignIn</span> <span class=\"search-result-import-path\">reachhigh/src/components/auth/SignIn.js</span>",
    "class"
  ],
  [
    "reachhigh/src/components/auth/signup.js~signup",
    "class/src/components/auth/SignUp.js~SignUp.html",
    "<span>SignUp</span> <span class=\"search-result-import-path\">reachhigh/src/components/auth/SignUp.js</span>",
    "class"
  ],
  [
    "reachhigh/src/components/tasks/taskview.js~taskview",
    "class/src/components/tasks/TaskView.js~TaskView.html",
    "<span>TaskView</span> <span class=\"search-result-import-path\">reachhigh/src/components/tasks/TaskView.js</span>",
    "class"
  ],
  [
    "reachhigh/src/components/tasks/tasks.js~tasks",
    "class/src/components/tasks/Tasks.js~Tasks.html",
    "<span>Tasks</span> <span class=\"search-result-import-path\">reachhigh/src/components/tasks/Tasks.js</span>",
    "class"
  ],
  [
    "reachhigh/src/stores/uistore.js~uistore",
    "class/src/stores/UIStore.js~UIStore.html",
    "<span>UIStore</span> <span class=\"search-result-import-path\">reachhigh/src/stores/UIStore.js</span>",
    "class"
  ],
  [
    "reachhigh/src/utils/auth.js~auth",
    "function/index.html#static-function-auth",
    "<span>auth</span> <span class=\"search-result-import-path\">reachhigh/src/utils/auth.js</span>",
    "function"
  ],
  [
    "reachhigh/src/utils/helpers.js~getdata",
    "function/index.html#static-function-getData",
    "<span>getData</span> <span class=\"search-result-import-path\">reachhigh/src/utils/helpers.js</span>",
    "function"
  ],
  [
    "reachhigh/src/utils/helpers.js~getinitialprops",
    "function/index.html#static-function-getInitialProps",
    "<span>getInitialProps</span> <span class=\"search-result-import-path\">reachhigh/src/utils/helpers.js</span>",
    "function"
  ],
  [
    "reachhigh/src/utils/auth.js~logout",
    "function/index.html#static-function-logout",
    "<span>logout</span> <span class=\"search-result-import-path\">reachhigh/src/utils/auth.js</span>",
    "function"
  ],
  [
    "reachhigh/src/utils/helpers.js~patchdata",
    "function/index.html#static-function-patchData",
    "<span>patchData</span> <span class=\"search-result-import-path\">reachhigh/src/utils/helpers.js</span>",
    "function"
  ],
  [
    "reachhigh/src/utils/helpers.js~postdata",
    "function/index.html#static-function-postData",
    "<span>postData</span> <span class=\"search-result-import-path\">reachhigh/src/utils/helpers.js</span>",
    "function"
  ],
  [
    "reachhigh/src/utils/helpers.js~renderif",
    "function/index.html#static-function-renderIf",
    "<span>renderIf</span> <span class=\"search-result-import-path\">reachhigh/src/utils/helpers.js</span>",
    "function"
  ],
  [
    "reachhigh/src/utils/helpers.js~runinactionutil",
    "function/index.html#static-function-runInActionUtil",
    "<span>runInActionUtil</span> <span class=\"search-result-import-path\">reachhigh/src/utils/helpers.js</span>",
    "function"
  ],
  [
    "reachhigh/src/utils/helpers.js~setclassprops",
    "function/index.html#static-function-setClassProps",
    "<span>setClassProps</span> <span class=\"search-result-import-path\">reachhigh/src/utils/helpers.js</span>",
    "function"
  ],
  [
    "reachhigh/src/utils/auth.js~signin",
    "function/index.html#static-function-signin",
    "<span>signin</span> <span class=\"search-result-import-path\">reachhigh/src/utils/auth.js</span>",
    "function"
  ],
  [
    "reachhigh/src/utils/auth.js~withauthsync",
    "function/index.html#static-function-withAuthSync",
    "<span>withAuthSync</span> <span class=\"search-result-import-path\">reachhigh/src/utils/auth.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/components/auth/signin.js",
    "file/src/components/auth/SignIn.js.html",
    "src/components/auth/SignIn.js",
    "file"
  ],
  [
    "src/components/auth/signin.js~signin#render",
    "class/src/components/auth/SignIn.js~SignIn.html#instance-method-render",
    "src/components/auth/SignIn.js~SignIn#render",
    "method"
  ],
  [
    "src/components/auth/signup.js",
    "file/src/components/auth/SignUp.js.html",
    "src/components/auth/SignUp.js",
    "file"
  ],
  [
    "src/components/auth/signup.js~signup#render",
    "class/src/components/auth/SignUp.js~SignUp.html#instance-method-render",
    "src/components/auth/SignUp.js~SignUp#render",
    "method"
  ],
  [
    "src/components/goals/goals.js",
    "file/src/components/goals/Goals.js.html",
    "src/components/goals/Goals.js",
    "file"
  ],
  [
    "src/components/goals/goals.js~goals#componentdidmount",
    "class/src/components/goals/Goals.js~Goals.html#instance-method-componentDidMount",
    "src/components/goals/Goals.js~Goals#componentDidMount",
    "method"
  ],
  [
    "src/components/goals/goals.js~goals#constructor",
    "class/src/components/goals/Goals.js~Goals.html#instance-constructor-constructor",
    "src/components/goals/Goals.js~Goals#constructor",
    "method"
  ],
  [
    "src/components/goals/goals.js~goals#content",
    "class/src/components/goals/Goals.js~Goals.html#instance-member-content",
    "src/components/goals/Goals.js~Goals#content",
    "member"
  ],
  [
    "src/components/goals/goals.js~goals#render",
    "class/src/components/goals/Goals.js~Goals.html#instance-method-render",
    "src/components/goals/Goals.js~Goals#render",
    "method"
  ],
  [
    "src/components/home/home.js",
    "file/src/components/home/Home.js.html",
    "src/components/home/Home.js",
    "file"
  ],
  [
    "src/components/navigation/horizontalnavigation.js",
    "file/src/components/navigation/HorizontalNavigation.js.html",
    "src/components/navigation/HorizontalNavigation.js",
    "file"
  ],
  [
    "src/components/tasks/taskview.js",
    "file/src/components/tasks/TaskView.js.html",
    "src/components/tasks/TaskView.js",
    "file"
  ],
  [
    "src/components/tasks/taskview.js~taskview#componentdidmount",
    "class/src/components/tasks/TaskView.js~TaskView.html#instance-method-componentDidMount",
    "src/components/tasks/TaskView.js~TaskView#componentDidMount",
    "method"
  ],
  [
    "src/components/tasks/taskview.js~taskview#content",
    "class/src/components/tasks/TaskView.js~TaskView.html#instance-member-content",
    "src/components/tasks/TaskView.js~TaskView#content",
    "member"
  ],
  [
    "src/components/tasks/taskview.js~taskview#render",
    "class/src/components/tasks/TaskView.js~TaskView.html#instance-method-render",
    "src/components/tasks/TaskView.js~TaskView#render",
    "method"
  ],
  [
    "src/components/tasks/tasks.js",
    "file/src/components/tasks/Tasks.js.html",
    "src/components/tasks/Tasks.js",
    "file"
  ],
  [
    "src/components/tasks/tasks.js~tasks#componentdidmount",
    "class/src/components/tasks/Tasks.js~Tasks.html#instance-method-componentDidMount",
    "src/components/tasks/Tasks.js~Tasks#componentDidMount",
    "method"
  ],
  [
    "src/components/tasks/tasks.js~tasks#content",
    "class/src/components/tasks/Tasks.js~Tasks.html#instance-member-content",
    "src/components/tasks/Tasks.js~Tasks#content",
    "member"
  ],
  [
    "src/components/tasks/tasks.js~tasks#render",
    "class/src/components/tasks/Tasks.js~Tasks.html#instance-method-render",
    "src/components/tasks/Tasks.js~Tasks#render",
    "method"
  ],
  [
    "src/stores/authstore.js",
    "file/src/stores/AuthStore.js.html",
    "src/stores/AuthStore.js",
    "file"
  ],
  [
    "src/stores/authstore.js~authstore#constructor",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-constructor-constructor",
    "src/stores/AuthStore.js~AuthStore#constructor",
    "method"
  ],
  [
    "src/stores/authstore.js~authstore#login",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-member-login",
    "src/stores/AuthStore.js~AuthStore#login",
    "member"
  ],
  [
    "src/stores/authstore.js~authstore#logincredentials",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-member-loginCredentials",
    "src/stores/AuthStore.js~AuthStore#loginCredentials",
    "member"
  ],
  [
    "src/stores/authstore.js~authstore#loginerrors",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-member-loginErrors",
    "src/stores/AuthStore.js~AuthStore#loginErrors",
    "member"
  ],
  [
    "src/stores/authstore.js~authstore#loginloading",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-member-loginLoading",
    "src/stores/AuthStore.js~AuthStore#loginLoading",
    "member"
  ],
  [
    "src/stores/authstore.js~authstore#setclassprops",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-member-setClassProps",
    "src/stores/AuthStore.js~AuthStore#setClassProps",
    "member"
  ],
  [
    "src/stores/authstore.js~authstore#signup",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-member-signup",
    "src/stores/AuthStore.js~AuthStore#signup",
    "member"
  ],
  [
    "src/stores/authstore.js~authstore#signupdata",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-member-signupData",
    "src/stores/AuthStore.js~AuthStore#signupData",
    "member"
  ],
  [
    "src/stores/authstore.js~authstore#signuperrors",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-member-signupErrors",
    "src/stores/AuthStore.js~AuthStore#signupErrors",
    "member"
  ],
  [
    "src/stores/authstore.js~authstore#signuploading",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-member-signupLoading",
    "src/stores/AuthStore.js~AuthStore#signupLoading",
    "member"
  ],
  [
    "src/stores/authstore.js~authstore#uistore",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-member-uiStore",
    "src/stores/AuthStore.js~AuthStore#uiStore",
    "member"
  ],
  [
    "src/stores/authstore.js~authstore#validateemail",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-member-validateEmail",
    "src/stores/AuthStore.js~AuthStore#validateEmail",
    "member"
  ],
  [
    "src/stores/authstore.js~authstore#validatepassword",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-member-validatePassword",
    "src/stores/AuthStore.js~AuthStore#validatePassword",
    "member"
  ],
  [
    "src/stores/authstore.js~authstore#validatepasswordmatch",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-member-validatePasswordMatch",
    "src/stores/AuthStore.js~AuthStore#validatePasswordMatch",
    "member"
  ],
  [
    "src/stores/authstore.js~authstore#validatefields",
    "class/src/stores/AuthStore.js~AuthStore.html#instance-member-validatefields",
    "src/stores/AuthStore.js~AuthStore#validatefields",
    "member"
  ],
  [
    "src/stores/goalsstore.js",
    "file/src/stores/GoalsStore.js.html",
    "src/stores/GoalsStore.js",
    "file"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#calctasks",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-calcTasks",
    "src/stores/GoalsStore.js~GoalsStore#calcTasks",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#completedtasks",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-completedTasks",
    "src/stores/GoalsStore.js~GoalsStore#completedTasks",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#constructor",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-constructor-constructor",
    "src/stores/GoalsStore.js~GoalsStore#constructor",
    "method"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#currenttask",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-currentTask",
    "src/stores/GoalsStore.js~GoalsStore#currentTask",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#gettask",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-getTask",
    "src/stores/GoalsStore.js~GoalsStore#getTask",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#gettasks",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-getTasks",
    "src/stores/GoalsStore.js~GoalsStore#getTasks",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#getuser",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-getUser",
    "src/stores/GoalsStore.js~GoalsStore#getUser",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#goalicons",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-goalIcons",
    "src/stores/GoalsStore.js~GoalsStore#goalIcons",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#goals",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-goals",
    "src/stores/GoalsStore.js~GoalsStore#goals",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#goalssaving",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-goalsSaving",
    "src/stores/GoalsStore.js~GoalsStore#goalsSaving",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#ontaskcomplete",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-onTaskComplete",
    "src/stores/GoalsStore.js~GoalsStore#onTaskComplete",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#savegoals",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-saveGoals",
    "src/stores/GoalsStore.js~GoalsStore#saveGoals",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#selectgoal",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-selectGoal",
    "src/stores/GoalsStore.js~GoalsStore#selectGoal",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#selectedgoals",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-selectedGoals",
    "src/stores/GoalsStore.js~GoalsStore#selectedGoals",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#setclassprops",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-setClassProps",
    "src/stores/GoalsStore.js~GoalsStore#setClassProps",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#tasks",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-tasks",
    "src/stores/GoalsStore.js~GoalsStore#tasks",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#uistore",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-uiStore",
    "src/stores/GoalsStore.js~GoalsStore#uiStore",
    "member"
  ],
  [
    "src/stores/goalsstore.js~goalsstore#user",
    "class/src/stores/GoalsStore.js~GoalsStore.html#instance-member-user",
    "src/stores/GoalsStore.js~GoalsStore#user",
    "member"
  ],
  [
    "src/stores/uistore.js",
    "file/src/stores/UIStore.js.html",
    "src/stores/UIStore.js",
    "file"
  ],
  [
    "src/stores/uistore.js~uistore#modal",
    "class/src/stores/UIStore.js~UIStore.html#instance-member-modal",
    "src/stores/UIStore.js~UIStore#modal",
    "member"
  ],
  [
    "src/stores/uistore.js~uistore#setclassprops",
    "class/src/stores/UIStore.js~UIStore.html#instance-member-setClassProps",
    "src/stores/UIStore.js~UIStore#setClassProps",
    "member"
  ],
  [
    "src/stores/index.js",
    "file/src/stores/index.js.html",
    "src/stores/index.js",
    "file"
  ],
  [
    "src/utils/auth.js",
    "file/src/utils/auth.js.html",
    "src/utils/auth.js",
    "file"
  ],
  [
    "src/utils/helpers.js",
    "file/src/utils/helpers.js.html",
    "src/utils/helpers.js",
    "file"
  ]
]